apiVersion: v1 # версия api, которую использует k8s
kind: Pod      # тип ресурса, манифест которого описываем
metadata:      # дополнительные сведения о ресурсе
  name: nginx
spec:          # спецификация, в которой описываем контейнеры, которые будут использовать в поде
  containers:  # контейнер с именем nginx, использует образ nginx1.27. Который слушает 80 порт
  - name: nginx 
    image: nginx:1.27
    ports:
    - containerPort: 80
 