apiVersion: apps/v1
kind: Deployment    # тип ресурса, манифест которого описываем
metadata:
  name: nginx
  labels:
    app: nginx      # 
spec:
  replicas: 3       # желаемое кол-во реплик, которое нам необходимо поддерживать
  selector:         # 
    matchLabels:
      app: nginx
  template:         # здесь указывается то, какие поды будут создаваться деплойментом
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets: # указываем имя нашего секрета
      - name: registrySecret # подсказка для k8s, что данные для авторизации в container registry находятся в registrySecret
      containers:
      - name: nginx 
        image: {{ .Values.werf.image.app }} # шаблонная переменная Helm, которую werf автоматически заполняет именем Docker-образа, собранного для приложения app
        command: ["/goapp"] # добавим команду для запуска приложения
        ports:
        - containerPort: 80
